output "bucket_name" {
  description = "The name of the bucket."
  value       = module.private_buckets.bucket_name
}

output "bucket_domain_name" {
  description = "The bucket domain name."
  value       = module.private_buckets.bucket_domain_name
}

output "website_endpoint" {
  description = "The website endpoint."
  value       = module.private_buckets.website_endpoint
}

output "website_domain" {
  description = "The domain of the website endpoint."
  value       = module.private_buckets.website_domain
}

output "storage_admin_service_account_id" {
  description = "Service account ID of the Object storage admin."
  value       = module.private_buckets.storage_admin_service_account_id
}

output "storage_admin_access_key" {
  description = "Static access key of the autogenerated Object storage admin service account."
  value       = module.private_buckets.storage_admin_access_key
}

output "storage_admin_secret_key" {
  description = "Static secret key of the autogenerated Object storage admin service account."
  sensitive   = true
  value       = module.private_buckets.storage_admin_secret_key
}

output "kms_master_key_id" {
  description = "The KMS master key ID used for the server-side encryption."
  value       = module.private_buckets.kms_master_key_id
}

output "cm_certificate_id" {
  description = "Certificate ID of the generated HTTPS certificate in Yandex Cloud Certificate Manager"
  value       = module.private_buckets.cm_certificate_id
}
